services:
  mongo:
    image: mongo
    restart: always
    container_name: mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: 1234
      MONGO_INITDB_DATABASE: CryptoPortfolio
    ports:
      - "27017:27017"
    volumes:
      - ./init-mongo-db-with-collections.js:/docker-entrypoint-initdb.d/init-mongo-db-with-collections.js:ro
  portfolioapi:
    depends_on:
      - mongo
    container_name: portfolioapi
    build:
      dockerfile: ./Docker/CryptoPorfolio.Dockerfile
      context: ..\
    ports:
      - "5000:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Docker
    command:  run